development:
  adapter: redis
  url: redis://localhost:6379/0
  channel_prefix: myapp_development

test:
  adapter: async
  channel_prefix: my_app_test

production:
  adapter: redis
  url: redis://localhost:6379/0
  channel_prefix: my_app_production
